version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      web-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:45"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pub
    directory: /flutter_app
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/Denver
    open-pull-requests-limit: 5
    groups:
      flutter-dependencies:
        patterns:
          - "*"
