const STORAGE_KEY='consistifit_playable_demo_v1';
const RANKS=[['Iron III',0],['Iron II',50],['Iron I',100],['Bronze III',200],['Bronze II',350],['Bronze I',500],['Silver III',700],['Silver II',900],['Silver I',1100],['Gold III',1350],['Gold II',1550],['Gold I',1750],['Platinum III',1900],['Platinum II',2100],['Platinum I',2300],['Diamond III',2600],['Diamond II',3000],['Diamond I',3600],['Master',4500],['Grandmaster',6000]];
const PROGRAM=[
 {name:'Full Body A',exercises:[['Goblet Squat','Legs',3,8,10,90],['Dumbbell Bench Press','Chest',3,8,12,90],['Seated Cable Row','Back',3,8,12,90],['Romanian Deadlift','Hamstrings',2,8,10,105],['Lateral Raise','Shoulders',2,12,15,60],['Plank','Core',2,30,45,60]]},
 {name:'Full Body B',exercises:[['Leg Press','Legs',3,8,12,90],['Lat Pulldown','Back',3,8,12,90],['Dumbbell Shoulder Press','Shoulders',3,8,12,90],['Leg Curl','Hamstrings',2,10,15,75],['Dumbbell Curl','Biceps',2,10,15,60],['Dead Bug','Core',2,8,12,60]]},
 {name:'Full Body C',exercises:[['Split Squat','Legs',3,8,10,90],['Incline Dumbbell Press','Chest',3,8,12,90],['Chest-Supported Row','Back',3,8,12,90],['Hip Thrust','Glutes',2,8,12,90],['Triceps Pressdown','Triceps',2,10,15,60],['Calf Raise','Calves',2,12,20,60]]}
];
const SHOP=[
 {code:'frame_lime',name:'Lime Profile Frame',price:250,desc:'Cosmetic profile frame.'},
 {code:'title_consistent',name:'“Consistent” Title',price:180,desc:'Profile title cosmetic.'},
 {code:'xp_boost',name:'XP Booster',price:300,desc:'Adds 25% XP to your next completed workout.',repeat:true},
 {code:'streak_shield',name:'Streak Shield',price:400,desc:'Saved for a future missed planned day.',repeat:true}
];
let state=loadState();
let activeScreen='home';
let restTimer=null,restRemaining=0;
let toastTimer=null;
let deferredInstall=null;

function freshState(){return{version:1,profile:{name:'Matthew',xp:0,coins:200,rp:0,streak:0,longestStreak:0,lastStreakDate:null},demo:{dayOffset:0},daily:{date:'',steps:0,mobility:0,checkin:null,claimed:{},dayComplete:false,perfectClaimed:false},history:[],inventory:{},purchased:[],workout:{active:null}}}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return freshState();const parsed=JSON.parse(raw);return parsed&&parsed.version===1?parsed:freshState()}catch{return freshState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function demoDate(){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+(state.demo.dayOffset||0));return d}
function keyForDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayLabel(d){return d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}
function isTrainingDay(d=demoDate()){return [1,3,5].includes(d.getDay())}
function previousDateKey(d){const p=new Date(d);p.setDate(p.getDate()-1);return keyForDate(p)}
function ensureDaily(){const now=demoDate(),key=keyForDate(now);if(state.daily.date===key)return;if(state.daily.date&&state.daily.dayComplete===false&&state.profile.lastStreakDate===state.daily.date){state.profile.streak=0}state.daily={date:key,steps:0,mobility:0,checkin:null,claimed:{},dayComplete:false,perfectClaimed:false};saveState()}
function currentRank(rp=state.profile.rp){let current=RANKS[0];for(const rank of RANKS){if(rp<rank[1])break;current=rank}return current}
function nextRank(){const rp=state.profile.rp;return RANKS.find(r=>r[1]>rp)||null}
function accountLevel(){return 1+Math.floor(state.profile.xp/1000)}
function workoutCount(){return state.history.filter(h=>h.type==='workout'&&h.eligible).length}
function todayTemplate(){return PROGRAM[workoutCount()%PROGRAM.length]}
function todayPlanName(){return isTrainingDay()?todayTemplate().name:'Recovery + Mobility'}
function stats(){const workouts=state.history.filter(h=>h.type==='workout');return{workouts:workouts.length,minutes:workouts.reduce((a,h)=>a+(h.duration||0),0),volume:workouts.reduce((a,h)=>a+(h.volume||0),0)}}
function rewardOnce(code,{rp=0,xp=0,coins=0}){ensureDaily();if(state.daily.claimed[code])return false;if(code==='workout'&&state.inventory.xp_boost>0){xp=Math.round(xp*1.25);state.inventory.xp_boost--;}
 state.daily.claimed[code]={rp,xp,coins,at:new Date().toISOString()};state.profile.rp=Math.max(0,state.profile.rp+rp);state.profile.xp+=xp;state.profile.coins+=coins;saveState();return true}
function markDayComplete(){ensureDaily();if(state.daily.dayComplete)return;state.daily.dayComplete=true;const key=state.daily.date;const prev=previousDateKey(demoDate());if(state.profile.lastStreakDate===prev)state.profile.streak+=1;else if(state.profile.lastStreakDate!==key)state.profile.streak=1;state.profile.longestStreak=Math.max(state.profile.longestStreak,state.profile.streak);state.profile.lastStreakDate=key;saveState()}
function evaluateDaily(){ensureDaily();const training=isTrainingDay();const primary=training?!!state.daily.claimed.workout:!!state.daily.claimed.recovery;if(primary)markDayComplete();const required=training?['workout','steps','mobility','checkin']:['recovery','steps','checkin'];if(required.every(k=>!!state.daily.claimed[k])&&!state.daily.perfectClaimed){state.daily.perfectClaimed=true;rewardOnce('perfect',{rp:15,xp:50,coins:25});toast('Perfect day bonus: +15 RP');}saveState()}
function formatNum(n){return Math.round(n).toLocaleString()}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function showScreen(name){activeScreen=name;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function questDone(code){return !!state.daily.claimed[code]}
function questRow({code,icon,title,desc,reward,extra=''}){const done=questDone(code);return `<div class="quest ${done?'done':''}"><div class="quest-icon">${done?'✓':icon}</div><div><h3>${title}</h3><p>${desc}</p>${extra}</div><div class="reward">${done?'DONE':reward}</div></div>`}
function renderTop(){const rank=currentRank();document.getElementById('wallet').textContent=`◈ ${formatNum(state.profile.coins)} · ${rank[0]}`}
function renderHome(){const d=demoDate(),training=isTrainingDay(d),rank=currentRank(),next=nextRank(),statsData=stats();const progress=next?Math.max(0,Math.min(100,(state.profile.rp-rank[1])/(next[1]-rank[1])*100)):100;document.getElementById('screen-home').innerHTML=`
 <div class="eyebrow">${dayLabel(d)}${state.demo.dayOffset?' · DEMO DAY':''}</div><h1 class="headline">Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${escapeHtml(state.profile.name)}.</h1><div class="sub">Build consistency one planned day at a time.</div>
 <div class="hero"><img src="https://images.pexels.com/photos/11432959/pexels-photo-11432959.jpeg?cs=srgb&dl=pexels-marius-aholou-193600353-11432959.jpg&fm=jpg" alt="Athlete training with dumbbells" referrerpolicy="no-referrer"><div class="hero-copy"><div class="eyebrow">TODAY'S PLAN</div><h2>${todayPlanName()}</h2><p>${training?'Scheduled strength workout · about 45 minutes':'Planned recovery counts toward your consistency.'}</p><div class="hero-actions">${training?`<button class="primary" onclick="startWorkout()">${state.workout.active?'Resume workout':'Start workout'}</button>`:`<button class="primary" onclick="showScreen('missions')">Log recovery</button>`}<button class="ghost" onclick="openPlanSheet()">View plan</button></div></div></div>
 <div class="section-title">CURRENT PROGRESS</div><div class="rank-hero"><div class="eyebrow">CONSISTENCY RANK</div><div class="rank-name">${rank[0]}</div><div class="row between"><span class="muted">${state.profile.rp} RP</span><span class="muted">${next?`${next[1]-state.profile.rp} RP to ${next[0]}`:'Highest rank'}</span></div><div class="bar" style="margin-top:10px"><i style="width:${progress}%"></i></div></div>
 <div class="section-title">ACCOUNT</div><div class="stat-grid"><div class="stat"><strong>${accountLevel()}</strong><span>LEVEL</span></div><div class="stat"><strong>${state.profile.streak}</strong><span>DAY STREAK</span></div><div class="stat"><strong>${statsData.workouts}</strong><span>WORKOUTS</span></div></div>
 <div class="section-title">QUICK LOG</div><div class="card"><div class="row between"><div><b>Steps today</b><div class="sub">8,000 steps completes a daily quest.</div></div><span class="badge">${formatNum(state.daily.steps)} / 8,000</span></div><div class="input-row"><input id="homeSteps" type="number" min="0" step="100" value="${state.daily.steps}" inputmode="numeric"><button class="primary small" onclick="saveSteps('homeSteps')">Save</button></div></div>`}
function renderMissions(){const training=isTrainingDay(),stepsExtra=`<div class="input-row"><input id="missionSteps" type="number" min="0" step="100" value="${state.daily.steps}" inputmode="numeric"><button class="ghost small" onclick="saveSteps('missionSteps')">Save</button></div>`;const mobilityExtra=`<div class="input-row"><input id="mobilityMinutes" type="number" min="0" step="1" value="${state.daily.mobility}" inputmode="numeric"><button class="ghost small" onclick="saveMobility()">Save min</button></div>`;const checkButtons=questDone('checkin')?'':`<div class="input-row"><button class="ghost small" onclick="completeCheckin('Ready')">Ready</button><button class="ghost small" onclick="completeCheckin('Tired')">Tired</button><button class="ghost small" onclick="completeCheckin('Sore')">Sore</button></div>`;const complete=Object.keys(state.daily.claimed).filter(k=>k!=='perfect').length;document.getElementById('screen-missions').innerHTML=`<div class="eyebrow">DAILY MISSIONS</div><h1 class="headline">${complete} completed</h1><div class="sub">Quest rewards can only be earned once per demo day. Extra workouts do not farm RP.</div><div class="card">${training?questRow({code:'workout',icon:'🏋',title:'Scheduled workout',desc:'Complete at least 70% of your planned working sets.',reward:'+30 RP'}) : questRow({code:'recovery',icon:'↻',title:'Planned recovery',desc:'Log at least 10 minutes of mobility or recovery work.',reward:'+15 RP',extra:mobilityExtra})}${questRow({code:'steps',icon:'👟',title:'8,000 steps',desc:`Current: ${formatNum(state.daily.steps)} steps`,reward:'+10 RP',extra:stepsExtra})}${training?questRow({code:'mobility',icon:'◇',title:'Mobility reset',desc:'Log at least 10 minutes of mobility.',reward:'+10 RP',extra:mobilityExtra}):''}${questRow({code:'checkin',icon:'●',title:'Training check-in',desc:state.daily.checkin?`Today: ${state.daily.checkin}`:'Log how your body feels today.',reward:'+5 RP',extra:checkButtons})}</div>${state.daily.perfectClaimed?'<div class="card"><b class="accent">Perfect day achieved</b><div class="sub">All daily missions complete · bonus awarded.</div></div>':''}`}
function renderRank(){const rank=currentRank(),next=nextRank();document.getElementById('screen-rank').innerHTML=`<div class="eyebrow">CONSISTENCY RANK</div><h1 class="headline">${rank[0]}</h1><div class="sub">${state.profile.rp} RP${next?` · ${next[1]-state.profile.rp} RP to ${next[0]}`:' · Grandmaster reached'}</div><div class="card"><b>How rank works</b><div class="sub" style="margin-top:6px">Scheduled training, recovery and healthy daily missions earn RP. Account XP is permanent. This local demo does not yet apply end-of-week rank decay.</div></div><div class="section-title">RANK LADDER</div><div class="card">${[...RANKS].reverse().map(r=>`<div class="ladder-row ${r[0]===rank[0]?'current':''}"><span>${r[0]}${r[0]===rank[0]?' · YOU':''}</span><span>${formatNum(r[1])} RP</span></div>`).join('')}</div>`}
function renderProgress(){const s=stats();document.getElementById('screen-progress').innerHTML=`<div class="eyebrow">PROGRESS</div><h1 class="headline">Your training log.</h1><div class="stat-grid"><div class="stat"><strong>${s.workouts}</strong><span>WORKOUTS</span></div><div class="stat"><strong>${s.minutes}</strong><span>MINUTES</span></div><div class="stat"><strong>${formatNum(s.volume)}</strong><span>VOLUME LB</span></div></div><div class="section-title">WORKOUT HISTORY</div><div class="card">${state.history.length?state.history.slice().reverse().map(h=>`<div class="history-row"><b>${escapeHtml(h.name)}</b><small>${h.date} · ${h.duration} min · ${formatNum(h.volume)} lb · ${h.completedSets}/${h.totalSets} sets${h.eligible?' · RP earned':' · partial'}</small></div>`).join(''):'<div class="sub">Complete your first workout and it will appear here.</div>'}</div>`}
function renderProfile(){const inv=Object.entries(state.inventory).filter(([,v])=>v>0);document.getElementById('screen-profile').innerHTML=`<div class="eyebrow">PROFILE</div><h1 class="headline">${escapeHtml(state.profile.name)}</h1><div class="sub">${currentRank()[0]} · Level ${accountLevel()} · ${state.profile.streak}-day streak</div><div class="section-title">EDIT PROFILE</div><div class="card"><label class="sub">Display name</label><div class="input-row"><input id="profileName" value="${escapeHtml(state.profile.name)}" maxlength="24"><button class="primary small" onclick="saveProfileName()">Save</button></div></div><div class="section-title">REWARDS</div><div class="card"><div class="row between"><div><b>${formatNum(state.profile.coins)} Coins</b><div class="sub">Spend Coins on cosmetics and utilities. Never RP.</div></div><button class="primary small" onclick="openShop()">Shop</button></div><div class="inventory" style="margin-top:12px">${inv.length?inv.map(([k,v])=>`<span>${inventoryName(k)} ×${v}</span>`).join(''):'<span>No items yet</span>'}</div></div><div class="section-title">HEALTH + REMINDERS</div><div class="card"><button class="sheet-option" onclick="toast('Health sync is available in the Flutter phone build')"><span><b>Apple Health / Health Connect</b><small class="sub">Native phone build</small></span><span>›</span></button><button class="sheet-option" onclick="toast('Workout reminders are available in the Flutter phone build')"><span><b>Workout reminders</b><small class="sub">Native phone build</small></span><span>›</span></button></div><div class="section-title">DEMO CONTROLS</div><div class="card"><div class="demo-note">Use these controls to test multiple days of progression without waiting for real calendar days. Your normal data stays local to this browser.</div><div class="row" style="margin-top:12px;flex-wrap:wrap"><button class="ghost small" onclick="advanceDemoDay()">Advance demo day</button><button class="ghost small" onclick="returnToToday()">Return to today</button><button class="danger small" onclick="resetDemo()">Reset all data</button></div><div class="sub" style="margin-top:10px">Demo offset: ${state.demo.dayOffset||0} day(s)</div></div>`}
function renderAll(){ensureDaily();renderTop();renderHome();renderMissions();renderRank();renderProgress();renderProfile();document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${activeScreen}`));document.querySelectorAll('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===activeScreen))}
function saveSteps(id){const el=document.getElementById(id);const value=Math.max(0,Number(el.value)||0);state.daily.steps=Math.round(value);if(value>=8000&&rewardOnce('steps',{rp:10,xp:50,coins:25}))toast('Steps quest complete: +10 RP');saveState();evaluateDaily();renderAll()}
function saveMobility(){const value=Math.max(0,Number(document.getElementById('mobilityMinutes').value)||0);state.daily.mobility=Math.round(value);if(value>=10){const training=isTrainingDay();const code=training?'mobility':'recovery';const reward=training?{rp:10,xp:50,coins:25}:{rp:15,xp:80,coins:30};if(rewardOnce(code,reward))toast(`${training?'Mobility':'Recovery'} quest complete: +${reward.rp} RP`)}saveState();evaluateDaily();renderAll()}
function completeCheckin(value){state.daily.checkin=value;if(rewardOnce('checkin',{rp:5,xp:20,coins:10}))toast('Check-in complete: +5 RP');saveState();evaluateDaily();renderAll()}
function lastWeight(exercise){for(const h of [...state.history].reverse()){if(!h.sets)continue;const found=h.sets.find(s=>s.exercise===exercise&&s.done&&s.weight>0);if(found)return found.weight}return 0}
function startWorkout(){if(!isTrainingDay()){showScreen('missions');toast('Today is a planned recovery day');return}if(!state.workout.active){const template=todayTemplate();state.workout.active={name:template.name,startedAt:Date.now(),exerciseIndex:0,exercises:template.exercises.map(e=>({name:e[0],muscle:e[1],repMin:e[2]===2&&e[3]===30?30:e[3],repMax:e[4],rest:e[5],sets:Array.from({length:e[2]},(_,i)=>({number:i+1,weight:lastWeight(e[0]),reps:e[3],done:false}))}))};saveState()}renderWorkout();document.getElementById('workoutOverlay').classList.add('show');document.body.style.overflow='hidden'}
function closeWorkout(){document.getElementById('workoutOverlay').classList.remove('show');document.body.style.overflow='';clearInterval(restTimer);restTimer=null;restRemaining=0}
function renderWorkout(){const w=state.workout.active;if(!w)return;const ex=w.exercises[w.exerciseIndex];const done=w.exercises.flatMap(e=>e.sets).filter(s=>s.done).length,total=w.exercises.flatMap(e=>e.sets).length;document.getElementById('workoutContent').innerHTML=`<div class="workout-head"><div class="row between"><button class="ghost small" onclick="closeWorkout()">← Back</button><div style="text-align:center"><div class="eyebrow">ACTIVE WORKOUT</div><b>${w.name}</b></div><span class="badge">${done}/${total}</span></div></div><div class="exercise-tabs">${w.exercises.map((e,i)=>`<button class="${i===w.exerciseIndex?'active':''}" onclick="selectExercise(${i})">${i+1}. ${e.name}</button>`).join('')}</div><div class="workout-body"><div id="restBox" class="rest ${restRemaining>0?'show':''}"><div><div class="eyebrow">REST</div><strong id="restText">${formatRest(restRemaining)}</strong></div><div><button class="ghost small" onclick="adjustRest(-15)">−15</button> <button class="ghost small" onclick="skipRest()">Skip</button> <button class="ghost small" onclick="adjustRest(15)">+15</button></div></div><div class="eyebrow">EXERCISE ${w.exerciseIndex+1} / ${w.exercises.length}</div><div class="exercise-title">${ex.name}</div><div class="sub">${ex.muscle} · ${ex.sets.length} sets · ${ex.repMin}–${ex.repMax} reps</div><div class="section-title">WORKING SETS</div><div class="set-grid header"><span>SET</span><span>WEIGHT LB</span><span>REPS</span><span>DONE</span></div>${ex.sets.map((s,si)=>`<div class="set-grid"><b>${s.number}</b><input type="number" min="0" step="5" value="${s.weight}" onchange="setSetValue(${w.exerciseIndex},${si},'weight',this.value)"><input type="number" min="0" step="1" value="${s.reps}" onchange="setSetValue(${w.exerciseIndex},${si},'reps',this.value)"><button class="set-check ${s.done?'done':''}" onclick="toggleWorkoutSet(${w.exerciseIndex},${si})">${s.done?'✓':'○'}</button></div>`).join('')}<div class="section-title">SESSION</div><div class="card"><div class="row between"><span class="muted">Completed sets</span><b>${done} / ${total}</b></div><div class="bar" style="margin-top:10px"><i style="width:${Math.round(done/total*100)}%"></i></div></div></div><div class="finishbar"><button class="primary" onclick="openFinishWorkout()">Finish Workout</button></div>`}
function selectExercise(i){state.workout.active.exerciseIndex=i;saveState();renderWorkout()}
function setSetValue(ei,si,field,value){const set=state.workout.active.exercises[ei].sets[si];set[field]=Math.max(0,Number(value)||0);saveState()}
function toggleWorkoutSet(ei,si){const ex=state.workout.active.exercises[ei],set=ex.sets[si];set.done=!set.done;saveState();if(set.done)startRest(ex.rest);renderWorkout()}
function formatRest(s){const m=Math.floor(s/60),sec=s%60;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function startRest(seconds){clearInterval(restTimer);restRemaining=seconds;restTimer=setInterval(()=>{restRemaining=Math.max(0,restRemaining-1);const txt=document.getElementById('restText'),box=document.getElementById('restBox');if(txt)txt.textContent=formatRest(restRemaining);if(restRemaining===0){clearInterval(restTimer);restTimer=null;if(box)box.classList.remove('show');toast('Rest complete')}},1000)}
function adjustRest(delta){restRemaining=Math.max(0,Math.min(600,restRemaining+delta));const txt=document.getElementById('restText');if(txt)txt.textContent=formatRest(restRemaining);if(restRemaining===0)skipRest()}
function skipRest(){restRemaining=0;clearInterval(restTimer);restTimer=null;const box=document.getElementById('restBox');if(box)box.classList.remove('show')}
function openFinishWorkout(){const w=state.workout.active;if(!w)return;const done=w.exercises.flatMap(e=>e.sets).filter(s=>s.done).length;if(!done){toast('Complete at least one set first');return}openSheet(`<div class="eyebrow">POST-WORKOUT CHECK-IN</div><h2>How hard was today?</h2><div class="sub">This rating will be saved with your session.</div><div class="rating-grid" style="margin-top:14px"><button onclick="finishWorkout('Too Easy')"><b>Too easy</b><div class="sub">Increase next time</div></button><button onclick="finishWorkout('Good')"><b>Good</b><div class="sub">Stay on track</div></button><button onclick="finishWorkout('Hard')"><b>Hard</b><div class="sub">Watch recovery</div></button><button onclick="finishWorkout('Too Hard')"><b>Too hard</b><div class="sub">Back off next time</div></button></div>`)}
function finishWorkout(difficulty){const w=state.workout.active;if(!w)return;const allSets=w.exercises.flatMap(e=>e.sets.map(s=>({...s,exercise:e.name}))),doneSets=allSets.filter(s=>s.done),ratio=doneSets.length/allSets.length,eligible=ratio>=.7,duration=Math.max(1,Math.round((Date.now()-w.startedAt)/60000)),volume=doneSets.reduce((sum,s)=>sum+(s.weight*s.reps),0);state.history.push({type:'workout',date:state.daily.date,name:w.name,duration,volume,completedSets:doneSets.length,totalSets:allSets.length,difficulty,eligible,sets:allSets});state.workout.active=null;if(eligible&&rewardOnce('workout',{rp:30,xp:220,coins:85}))toast('Workout quest complete: +30 RP');state.daily.checkin=difficulty;if(rewardOnce('checkin',{rp:5,xp:20,coins:10})&&eligible){}saveState();evaluateDaily();closeSheet();closeWorkout();renderAll();setTimeout(()=>openSheet(`<div class="eyebrow">SESSION SAVED</div><h2>${eligible?'Workout complete':'Partial workout saved'}</h2><div class="stat-grid" style="margin:16px 0"><div class="stat"><strong>${duration}m</strong><span>DURATION</span></div><div class="stat"><strong>${doneSets.length}</strong><span>SETS</span></div><div class="stat"><strong>${formatNum(volume)}</strong><span>VOLUME LB</span></div></div><div class="card"><b>${eligible?'+30 RP · +220 XP · +85 Coins':'No scheduled-workout RP awarded'}</b><div class="sub" style="margin-top:5px">${eligible?'You completed at least 70% of the planned working sets.':'Complete at least 70% of planned working sets for the scheduled workout reward.'}</div></div><button class="primary" style="width:100%" onclick="closeSheet();showScreen('progress')">View progress</button>`),150)}
function openPlanSheet(){const template=todayTemplate();openSheet(`<div class="eyebrow">CONSISTIFIT FOUNDATION</div><h2>${todayPlanName()}</h2><div class="sub">Monday / Wednesday / Friday training. Planned recovery on the other days.</div>${isTrainingDay()?template.exercises.map(e=>`<button class="sheet-option" onclick="closeSheet()"><span><b>${e[0]}</b><small class="sub">${e[2]} sets · ${e[3]}–${e[4]} reps</small></span><span>›</span></button>`).join(''):'<div class="card"><b>Recovery day</b><div class="sub">10+ minutes of mobility completes today’s primary consistency task.</div></div>'}`)}
function openShop(){openSheet(`<div class="eyebrow">COIN SHOP</div><h2>${formatNum(state.profile.coins)} Coins</h2><div class="sub">Cosmetics and utilities only. RP is never sold.</div>${SHOP.map(item=>`<button class="sheet-option" onclick="purchaseItem('${item.code}')"><span><b>${item.name}</b><small class="sub">${item.desc}</small></span><span>${item.price} ◈</span></button>`).join('')}`)}
function inventoryName(code){return SHOP.find(i=>i.code===code)?.name||code}
function purchaseItem(code){const item=SHOP.find(i=>i.code===code);if(!item)return;if(!item.repeat&&state.purchased.includes(code)){toast('Already owned');return}if(state.profile.coins<item.price){toast('Not enough Coins');return}state.profile.coins-=item.price;state.inventory[code]=(state.inventory[code]||0)+1;if(!item.repeat)state.purchased.push(code);saveState();renderAll();openShop();toast(`${item.name} purchased`)}
function saveProfileName(){const v=document.getElementById('profileName').value.trim();if(!v)return toast('Enter a name');state.profile.name=v.slice(0,24);saveState();renderAll();toast('Profile updated')}
function advanceDemoDay(){if(!state.daily.dayComplete&&state.profile.lastStreakDate===state.daily.date)state.profile.streak=0;state.demo.dayOffset=(state.demo.dayOffset||0)+1;state.daily.date='';ensureDaily();renderAll();toast(`Advanced to ${dayLabel(demoDate())}`)}
function returnToToday(){state.demo.dayOffset=0;state.daily.date='';ensureDaily();renderAll();toast('Returned to today')}
function resetDemo(){if(!confirm('Reset all ConsistiFit demo progress on this device?'))return;localStorage.removeItem(STORAGE_KEY);state=freshState();ensureDaily();renderAll();toast('Demo progress reset')}
function openSheet(html){document.getElementById('sheetContent').innerHTML=html;document.getElementById('sheetBack').classList.add('show')}
function closeSheet(){document.getElementById('sheetBack').classList.remove('show')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;const btn=document.getElementById('installButton');if(btn)btn.classList.remove('hidden')});
async function installApp(){if(!deferredInstall){toast('Use your browser menu → Add to Home Screen');return}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}
window.addEventListener('load',()=>{ensureDaily();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(console.error)});
