const CF_HOME_FULL=[
 {name:'Home Full Body A',exercises:[['Dumbbell Goblet Squat','Quads · Glutes',3,8,12,90],['Dumbbell Bench Press','Chest · Triceps',3,8,12,90],['Bench-Supported Dumbbell Row','Back · Biceps',3,8,12,90],['Dumbbell Romanian Deadlift','Hamstrings · Glutes',3,8,12,105],['Dumbbell Lateral Raise','Shoulders',2,12,15,60],['Plank','Core',2,30,45,45]]},
 {name:'Home Full Body B',exercises:[['Dumbbell Reverse Lunge','Quads · Glutes',3,8,12,90],['Incline Dumbbell Bench Press','Chest · Triceps',3,8,12,90],['Chest-Supported Dumbbell Row','Back · Biceps',3,8,12,90],['Dumbbell Hip Thrust on Bench','Glutes · Hamstrings',3,10,15,90],['Seated Dumbbell Shoulder Press','Shoulders · Triceps',2,8,12,75],['Dead Bug','Core',2,8,12,45]]},
 {name:'Home Full Body C',exercises:[['Dumbbell Bulgarian Split Squat','Quads · Glutes',3,8,12,90],['Dumbbell Floor Press','Chest · Triceps',3,8,12,90],['One-Arm Dumbbell Row','Back · Biceps',3,8,12,90],['Single-Leg Dumbbell Romanian Deadlift','Hamstrings · Glutes',3,8,12,90],['Dumbbell Curl + Triceps Extension','Arms',2,10,15,60],['Bench Leg Raise','Core',2,10,15,45]]}
];
const CF_HOME_UL=[
 {name:'Home Upper A',exercises:[['Dumbbell Bench Press','Chest · Triceps',4,8,12,90],['Bench-Supported Dumbbell Row','Back · Biceps',4,8,12,90],['Seated Dumbbell Shoulder Press','Shoulders · Triceps',3,8,12,90],['Dumbbell Pullover on Bench','Lats · Chest',3,10,15,75],['Dumbbell Lateral Raise','Shoulders',2,12,15,60],['Dumbbell Curl','Biceps',2,10,15,60]]},
 {name:'Home Lower A',exercises:[['Dumbbell Goblet Squat','Quads · Glutes',4,8,12,105],['Dumbbell Romanian Deadlift','Hamstrings · Glutes',4,8,12,105],['Dumbbell Bulgarian Split Squat','Quads · Glutes',3,8,12,90],['Dumbbell Hip Thrust on Bench','Glutes',3,10,15,90],['Standing Dumbbell Calf Raise','Calves',3,12,20,60]]},
 {name:'Home Upper B',exercises:[['Incline Dumbbell Bench Press','Chest · Triceps',4,8,12,90],['Chest-Supported Dumbbell Row','Back · Biceps',4,8,12,90],['Arnold Press','Shoulders · Triceps',3,8,12,90],['Dumbbell Pullover on Bench','Lats · Chest',3,10,15,75],['Rear Delt Dumbbell Raise','Rear Delts',2,12,15,60],['Overhead Dumbbell Triceps Extension','Triceps',2,10,15,60]]},
 {name:'Home Lower B',exercises:[['Dumbbell Reverse Lunge','Quads · Glutes',4,8,12,90],['Dumbbell Sumo Squat','Quads · Glutes',3,10,15,90],['Single-Leg Dumbbell Romanian Deadlift','Hamstrings · Glutes',3,8,12,90],['Dumbbell Step-Up on Bench','Quads · Glutes',3,8,12,75],['Standing Dumbbell Calf Raise','Calves',3,12,20,60]]}
];
const CF_GYM_FULL=[
 {name:'Machine Full Body A',exercises:[['Leg Press','Quads · Glutes',3,8,12,90],['Machine Chest Press','Chest · Triceps',3,8,12,90],['Seated Row Machine','Back · Biceps',3,8,12,90],['Seated Leg Curl','Hamstrings',3,10,15,75],['Cable Lateral Raise','Shoulders',2,12,15,60],['Cable Crunch','Core',2,10,15,60]]},
 {name:'Machine Full Body B',exercises:[['Leg Extension','Quads',3,10,15,75],['Lat Pulldown Machine','Back · Biceps',3,8,12,90],['Shoulder Press Machine','Shoulders · Triceps',3,8,12,90],['Leg Curl Machine','Hamstrings',3,10,15,75],['Pec Deck','Chest',2,10,15,60],['Cable Curl','Biceps',2,10,15,60]]},
 {name:'Machine Full Body C',exercises:[['Leg Press','Quads · Glutes',3,10,15,90],['Machine Chest Press','Chest · Triceps',3,8,12,90],['Seated Row Machine','Back · Biceps',3,10,15,90],['Hip Abduction Machine','Glutes',3,12,20,60],['Calf Raise Machine','Calves',3,12,20,60],['Cable Triceps Pressdown','Triceps',2,10,15,60]]}
];
const CF_GYM_UL=[
 {name:'Machine Upper A',exercises:[['Machine Chest Press','Chest · Triceps',4,8,12,90],['Seated Row Machine','Back · Biceps',4,8,12,90],['Shoulder Press Machine','Shoulders · Triceps',3,8,12,90],['Lat Pulldown Machine','Back · Biceps',3,8,12,90],['Pec Deck','Chest',2,10,15,60],['Cable Curl','Biceps',2,10,15,60]]},
 {name:'Machine Lower A',exercises:[['Leg Press','Quads · Glutes',4,8,12,105],['Leg Curl Machine','Hamstrings',4,10,15,75],['Leg Extension','Quads',3,10,15,75],['Hip Abduction Machine','Glutes',3,12,20,60],['Calf Raise Machine','Calves',3,12,20,60]]},
 {name:'Machine Upper B',exercises:[['Machine Chest Press','Chest · Triceps',4,10,15,90],['Lat Pulldown Machine','Back · Biceps',4,8,12,90],['Seated Row Machine','Back · Biceps',3,10,15,90],['Reverse Pec Deck','Rear Delts',3,12,15,60],['Cable Lateral Raise','Shoulders',2,12,15,60],['Cable Triceps Pressdown','Triceps',2,10,15,60]]},
 {name:'Machine Lower B',exercises:[['Leg Press','Quads · Glutes',4,10,15,105],['Leg Curl Machine','Hamstrings',4,8,12,75],['Leg Extension','Quads',3,12,15,75],['Hip Abduction Machine','Glutes',3,12,20,60],['Calf Raise Machine','Calves',3,12,20,60]]}
];
const CF_EQUIPMENT=[
 ['dumbbells','Dumbbells'],['bench','Bench'],['barbell','Barbell + plates'],['rack','Squat rack'],['kettlebell','Kettlebell'],['bands','Resistance bands'],['pullup','Pull-up bar'],['cable','Cable station'],['legpress','Leg press'],['legextension','Leg extension'],['legcurl','Leg curl'],['chestpress','Chest press machine'],['shoulderpress','Shoulder press machine'],['rowmachine','Seated row machine'],['latpulldown','Lat pulldown'],['pecdeck','Pec deck / rear delt'],['hipabduction','Hip abduction machine'],['calfraise','Calf raise machine'],['cardio','Cardio machine']
];
function cfEnsurePlan(){if(!state.plan)state.plan={mode:'home',goal:'muscle',days:3,minutes:45,equipment:['dumbbells','bench']};if(!Array.isArray(state.plan.equipment))state.plan.equipment=['dumbbells','bench'];state.plan.days=Math.max(2,Math.min(6,Number(state.plan.days)||3));state.plan.minutes=[30,45,60,75].includes(Number(state.plan.minutes))?Number(state.plan.minutes):45;saveState();}
function cfTrainingDays(){cfEnsurePlan();return ({2:[1,4],3:[1,3,5],4:[1,2,4,5],5:[1,2,3,5,6],6:[1,2,3,4,5,6]})[state.plan.days]||[1,3,5]}
isTrainingDay=function(d=demoDate()){return cfTrainingDays().includes(d.getDay())};
function cfPlanName(){cfEnsurePlan();const goal=state.plan.goal==='strength'?'Strength':state.plan.goal==='habit'?'Habit':'Muscle';if(state.plan.mode==='home')return `ConsistiFit Home ${goal}`;if(state.plan.mode==='gym')return `ConsistiFit Machine ${goal}`;return `ConsistiFit Custom ${goal}`}
function cfEquipmentLabel(){cfEnsurePlan();if(state.plan.mode==='home')return 'Dumbbells + adjustable bench + bodyweight';if(state.plan.mode==='gym')return 'Machines + cables + cardio equipment';const labels=CF_EQUIPMENT.filter(([key])=>state.plan.equipment.includes(key)).map(([,label])=>label);return labels.length?labels.join(' · '):'Bodyweight only'}
function cfHas(key){return state.plan.equipment.includes(key)}
function cfPick(candidates){for(const candidate of candidates){if(candidate[0].every(cfHas))return candidate[1]}return candidates[candidates.length-1][1]}
function cfCustomFull(){return [
 {name:'Custom Full Body A',exercises:[
  cfPick([[['barbell','rack'],['Back Squat','Quads · Glutes',3,6,10,120]],[['legpress'],['Leg Press','Quads · Glutes',3,8,12,90]],[['dumbbells'],['Dumbbell Goblet Squat','Quads · Glutes',3,8,12,90]],[['kettlebell'],['Kettlebell Goblet Squat','Quads · Glutes',3,8,12,90]],[['bands'],['Band-Resisted Squat','Quads · Glutes',3,10,15,75]],[[],['Tempo Bodyweight Squat','Quads · Glutes',3,12,20,60]]]),
  cfPick([[['barbell','bench','rack'],['Barbell Bench Press','Chest · Triceps',3,6,10,120]],[['dumbbells','bench'],['Dumbbell Bench Press','Chest · Triceps',3,8,12,90]],[['chestpress'],['Machine Chest Press','Chest · Triceps',3,8,12,90]],[['cable'],['Standing Cable Chest Press','Chest · Triceps',3,10,15,75]],[['dumbbells'],['Dumbbell Floor Press','Chest · Triceps',3,8,12,90]],[[],['Push-up','Chest · Triceps',3,8,20,60]]]),
  cfPick([[['rowmachine'],['Seated Row Machine','Back · Biceps',3,8,12,90]],[['cable'],['Seated Cable Row','Back · Biceps',3,8,12,90]],[['dumbbells'],['One-Arm Dumbbell Row','Back · Biceps',3,8,12,90]],[['barbell'],['Barbell Row','Back · Biceps',3,6,10,105]],[['bands'],['Resistance Band Row','Back · Biceps',3,10,15,75]],[[],['Prone Reverse Snow Angel','Upper Back',3,10,15,60]]]),
  cfPick([[['barbell'],['Barbell Romanian Deadlift','Hamstrings · Glutes',3,6,10,120]],[['dumbbells'],['Dumbbell Romanian Deadlift','Hamstrings · Glutes',3,8,12,105]],[['kettlebell'],['Kettlebell Romanian Deadlift','Hamstrings · Glutes',3,8,12,90]],[['legcurl'],['Leg Curl Machine','Hamstrings',3,10,15,75]],[['bands'],['Band Good Morning','Hamstrings · Glutes',3,10,15,75]],[[],['Glute Bridge','Hamstrings · Glutes',3,12,20,60]]]),
  cfPick([[['dumbbells'],['Dumbbell Shoulder Press','Shoulders · Triceps',3,8,12,90]],[['shoulderpress'],['Shoulder Press Machine','Shoulders · Triceps',3,8,12,90]],[['barbell'],['Barbell Overhead Press','Shoulders · Triceps',3,6,10,105]],[['cable'],['Cable Lateral Raise','Shoulders',3,12,15,60]],[['bands'],['Band Shoulder Press','Shoulders · Triceps',3,10,15,75]],[[],['Pike Push-up','Shoulders · Triceps',3,6,12,60]]]),
  ['Plank','Core',2,30,45,45]
 ]},
 {name:'Custom Full Body B',exercises:[
  cfPick([[['legextension'],['Leg Extension','Quads',3,10,15,75]],[['dumbbells'],['Dumbbell Reverse Lunge','Quads · Glutes',3,8,12,90]],[['kettlebell'],['Kettlebell Reverse Lunge','Quads · Glutes',3,8,12,90]],[['bands'],['Band Split Squat','Quads · Glutes',3,10,15,75]],[[],['Reverse Lunge','Quads · Glutes',3,10,15,60]]]),
  cfPick([[['latpulldown'],['Lat Pulldown Machine','Back · Biceps',3,8,12,90]],[['pullup'],['Pull-up / Assisted Pull-up','Back · Biceps',3,5,10,105]],[['cable'],['Cable Lat Pulldown','Back · Biceps',3,8,12,90]],[['dumbbells','bench'],['Dumbbell Pullover on Bench','Lats · Chest',3,10,15,75]],[['bands'],['Band Lat Pulldown','Back · Biceps',3,10,15,75]],[[],['Prone Lat Sweep','Back',3,10,15,60]]]),
  cfPick([[['dumbbells','bench'],['Incline Dumbbell Bench Press','Chest · Triceps',3,8,12,90]],[['chestpress'],['Machine Chest Press','Chest · Triceps',3,10,15,90]],[['pecdeck'],['Pec Deck','Chest',3,10,15,60]],[['bands'],['Band Chest Press','Chest · Triceps',3,10,15,75]],[[],['Push-up','Chest · Triceps',3,8,20,60]]]),
  cfPick([[['legcurl'],['Leg Curl Machine','Hamstrings',3,10,15,75]],[['dumbbells'],['Dumbbell Romanian Deadlift','Hamstrings · Glutes',3,8,12,105]],[['barbell'],['Barbell Romanian Deadlift','Hamstrings · Glutes',3,6,10,120]],[['bands'],['Band Leg Curl','Hamstrings',3,12,20,60]],[[],['Single-Leg Glute Bridge','Hamstrings · Glutes',3,10,15,60]]]),
  cfPick([[['cable'],['Cable Curl','Biceps',2,10,15,60]],[['dumbbells'],['Dumbbell Curl','Biceps',2,10,15,60]],[['barbell'],['Barbell Curl','Biceps',2,8,12,60]],[['bands'],['Band Curl','Biceps',2,12,20,45]],[[],['Side Plank','Core',2,30,45,45]]]),
  ['Dead Bug','Core',2,8,12,45]
 ]},
 {name:'Custom Full Body C',exercises:[
  cfPick([[['dumbbells','bench'],['Dumbbell Bulgarian Split Squat','Quads · Glutes',3,8,12,90]],[['dumbbells'],['Dumbbell Split Squat','Quads · Glutes',3,8,12,90]],[['legpress'],['Single-Leg Press','Quads · Glutes',3,10,15,90]],[[],['Bulgarian Split Squat','Quads · Glutes',3,8,15,60]]]),
  cfPick([[['dumbbells'],['Dumbbell Floor Press','Chest · Triceps',3,8,12,90]],[['chestpress'],['Machine Chest Press','Chest · Triceps',3,8,12,90]],[['cable'],['Cable Fly','Chest',3,10,15,60]],[[],['Close-Grip Push-up','Chest · Triceps',3,8,20,60]]]),
  cfPick([[['dumbbells','bench'],['Chest-Supported Dumbbell Row','Back · Biceps',3,8,12,90]],[['rowmachine'],['Seated Row Machine','Back · Biceps',3,10,15,90]],[['cable'],['Cable Row','Back · Biceps',3,10,15,90]],[['bands'],['Resistance Band Row','Back · Biceps',3,12,20,60]],[[],['Prone Reverse Snow Angel','Upper Back',3,10,15,60]]]),
  cfPick([[['dumbbells','bench'],['Dumbbell Hip Thrust on Bench','Glutes',3,10,15,90]],[['cable'],['Cable Pull-Through','Glutes · Hamstrings',3,10,15,75]],[['hipabduction'],['Hip Abduction Machine','Glutes',3,12,20,60]],[['bands'],['Band Glute Bridge','Glutes',3,12,20,60]],[[],['Glute Bridge','Glutes',3,12,20,60]]]),
  cfPick([[['cable'],['Cable Triceps Pressdown','Triceps',2,10,15,60]],[['dumbbells'],['Dumbbell Curl + Triceps Extension','Arms',2,10,15,60]],[['bands'],['Band Curl + Pressdown','Arms',2,12,20,45]],[[],['Diamond Push-up','Triceps · Chest',2,6,15,60]]]),
  cfPick([[['calfraise'],['Calf Raise Machine','Calves',3,12,20,60]],[['dumbbells'],['Standing Dumbbell Calf Raise','Calves',3,12,20,60]],[[],['Side Plank','Core',2,30,45,45]]])
 ]}
]}
function cfCustomUpperLower(){const f=cfCustomFull();return [
 {name:'Custom Upper A',exercises:[f[0].exercises[1],f[0].exercises[2],f[0].exercises[4],f[1].exercises[1],f[1].exercises[4],f[2].exercises[4]]},
 {name:'Custom Lower A',exercises:[f[0].exercises[0],f[0].exercises[3],f[2].exercises[0],f[2].exercises[3],f[2].exercises[5]]},
 {name:'Custom Upper B',exercises:[f[1].exercises[2],f[1].exercises[1],f[2].exercises[2],f[0].exercises[4],f[1].exercises[4],f[2].exercises[4]]},
 {name:'Custom Lower B',exercises:[f[1].exercises[0],f[1].exercises[3],f[2].exercises[0],f[2].exercises[3],f[1].exercises[5]]}
]}
function cfApplyGoalAndTime(program){cfEnsurePlan();const max=state.plan.minutes<=30?4:state.plan.minutes<=45?5:6;return program.map(w=>({name:w.name,exercises:w.exercises.slice(0,max).map((e,i)=>{const x=[...e];if(state.plan.goal==='strength'&&i<4&&x[3]<20){x[2]=Math.max(3,x[2]);x[3]=5;x[4]=8;x[5]=Math.max(120,x[5])}if(state.plan.goal==='habit'){x[2]=Math.min(2,x[2]);x[5]=Math.min(75,x[5])}return x})}))}
function cfProgram(){cfEnsurePlan();const upperLower=state.plan.days>=4;if(state.plan.mode==='home')return cfApplyGoalAndTime(upperLower?CF_HOME_UL:CF_HOME_FULL);if(state.plan.mode==='gym')return cfApplyGoalAndTime(upperLower?CF_GYM_UL:CF_GYM_FULL);return cfApplyGoalAndTime(upperLower?cfCustomUpperLower():cfCustomFull())}
todayTemplate=function(){const program=cfProgram();return program[workoutCount()%program.length]};
todayPlanName=function(){return isTrainingDay()?todayTemplate().name:'Recovery + Mobility'};
function cfModeLabel(){return state.plan.mode==='home'?'At Home':state.plan.mode==='gym'?'Gym Machines':'Custom Equipment'}
function cfPlanSummary(){return `${cfPlanName()} · ${cfModeLabel()} · ${state.plan.days} days/week · ${state.plan.minutes} min`}
function cfRenderPlanCard(){return `<div class="section-title">TRAINING PLAN</div><div class="card"><div class="row between"><div><b>${cfPlanName()}</b><div class="sub">${cfModeLabel()} · ${state.plan.days} days/week · ${state.plan.minutes} min</div></div><button class="primary small" onclick="openPlanBuilder()">Change</button></div><div class="sub" style="margin-top:10px">${escapeHtml(cfEquipmentLabel())}</div></div>`}
const cfOriginalRenderHome=renderHome;
renderHome=function(){cfEnsurePlan();const d=demoDate(),training=isTrainingDay(d),rank=currentRank(),next=nextRank(),statsData=stats(),template=todayTemplate();const progress=next?Math.max(0,Math.min(100,(state.profile.rp-rank[1])/(next[1]-rank[1])*100)):100;document.getElementById('screen-home').innerHTML=`
 <div class="eyebrow">${dayLabel(d)}${state.demo.dayOffset?' · DEMO DAY':''}</div><h1 class="headline">Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${escapeHtml(state.profile.name)}.</h1><div class="sub">Build consistency one planned day at a time.</div>
 <div class="hero"><img src="https://images.pexels.com/photos/11432959/pexels-photo-11432959.jpeg?cs=srgb&dl=pexels-marius-aholou-193600353-11432959.jpg&fm=jpg" alt="Athlete training with dumbbells" referrerpolicy="no-referrer"><div class="hero-copy"><div class="eyebrow">TODAY'S PLAN</div><h2>${todayPlanName()}</h2><p>${training?`${cfModeLabel()} · about ${state.plan.minutes} minutes · ${template.exercises.length} exercises`:'Planned recovery counts toward your consistency.'}</p><div class="hero-actions">${training?`<button class="primary" onclick="startWorkout()">${state.workout.active?'Resume workout':'Start workout'}</button>`:`<button class="primary" onclick="showScreen('missions')">Log recovery</button>`}<button class="ghost" onclick="openPlanSheet()">View plan</button></div></div></div>
 ${cfRenderPlanCard()}
 <div class="section-title">CURRENT PROGRESS</div><div class="rank-hero"><div class="eyebrow">CONSISTENCY RANK</div><div class="rank-name">${rank[0]}</div><div class="row between"><span class="muted">${state.profile.rp} RP</span><span class="muted">${next?`${next[1]-state.profile.rp} RP to ${next[0]}`:'Highest rank'}</span></div><div class="bar" style="margin-top:10px"><i style="width:${progress}%"></i></div></div>
 <div class="section-title">ACCOUNT</div><div class="stat-grid"><div class="stat"><strong>${accountLevel()}</strong><span>LEVEL</span></div><div class="stat"><strong>${state.profile.streak}</strong><span>DAY STREAK</span></div><div class="stat"><strong>${statsData.workouts}</strong><span>WORKOUTS</span></div></div>
 <div class="section-title">QUICK LOG</div><div class="card"><div class="row between"><div><b>Steps today</b><div class="sub">8,000 steps completes a daily quest.</div></div><span class="badge">${formatNum(state.daily.steps)} / 8,000</span></div><div class="input-row"><input id="homeSteps" type="number" min="0" step="100" value="${state.daily.steps}" inputmode="numeric"><button class="primary small" onclick="saveSteps('homeSteps')">Save</button></div></div>`}
const cfOriginalRenderProfile=renderProfile;
renderProfile=function(){cfOriginalRenderProfile();const screen=document.getElementById('screen-profile');const card=document.createElement('div');card.innerHTML=cfRenderPlanCard();screen.insertBefore(card,screen.children[3]||null)};
openPlanSheet=function(){cfEnsurePlan();const template=todayTemplate();openSheet(`<div class="eyebrow">${escapeHtml(cfPlanName())}</div><h2>${todayPlanName()}</h2><div class="sub">${escapeHtml(cfEquipmentLabel())}</div><div class="sub" style="margin-top:4px">${state.plan.days} training days/week · ${state.plan.minutes}-minute sessions</div>${isTrainingDay()?template.exercises.map(e=>`<button class="sheet-option" onclick="closeSheet()"><span><b>${e[0]}</b><small class="sub">${e[2]} sets · ${e[3]}–${e[4]} reps · ${e[5]}s rest</small></span><span>›</span></button>`).join(''):'<div class="card"><b>Recovery day</b><div class="sub">10+ minutes of mobility completes today’s primary consistency task.</div></div>'}<button class="primary" style="width:100%;margin-top:12px" onclick="openPlanBuilder()">Change training plan</button>`)};
function openPlanBuilder(){cfEnsurePlan();const eq=CF_EQUIPMENT.map(([key,label])=>`<label class="equipment-choice"><input type="checkbox" value="${key}" ${state.plan.equipment.includes(key)?'checked':''}><span>${label}</span></label>`).join('');openSheet(`<div class="eyebrow">BUILD YOUR PROGRAM</div><h2>Where are you training?</h2><div class="plan-mode-grid"><button class="plan-mode ${state.plan.mode==='home'?'selected':''}" onclick="cfSelectMode('home')"><b>At Home</b><small>Dumbbells + bench</small></button><button class="plan-mode ${state.plan.mode==='gym'?'selected':''}" onclick="cfSelectMode('gym')"><b>Gym Machines</b><small>Machines + cables</small></button><button class="plan-mode ${state.plan.mode==='custom'?'selected':''}" onclick="cfSelectMode('custom')"><b>Choose My Equipment</b><small>Build around what you have</small></button></div><div id="customEquipmentBox" class="${state.plan.mode==='custom'?'':'hidden'}"><div class="section-title">YOUR EQUIPMENT</div><div class="sub">Bodyweight is always available as a fallback. You choose your actual working weight during each workout.</div><div class="equipment-grid">${eq}</div></div><div class="section-title">GOAL</div><select id="cfGoal"><option value="muscle" ${state.plan.goal==='muscle'?'selected':''}>Build muscle</option><option value="strength" ${state.plan.goal==='strength'?'selected':''}>Get stronger</option><option value="habit" ${state.plan.goal==='habit'?'selected':''}>Build the habit</option></select><div class="section-title">SCHEDULE</div><label class="sub">Training days per week</label><select id="cfDays">${[2,3,4,5,6].map(n=>`<option value="${n}" ${state.plan.days===n?'selected':''}>${n} days</option>`).join('')}</select><label class="sub" style="display:block;margin-top:12px">Session length</label><select id="cfMinutes">${[30,45,60,75].map(n=>`<option value="${n}" ${state.plan.minutes===n?'selected':''}>${n} minutes</option>`).join('')}</select><div class="card" style="margin-top:16px"><b>How working weight works</b><div class="sub">The plan chooses exercises, sets and rep ranges. You enter the weight you actually use set-by-set during the workout.</div></div><button class="primary" style="width:100%" onclick="cfSavePlan()">Build & Save My Plan</button>`)}
function cfSelectMode(mode){state.plan.mode=mode;saveState();openPlanBuilder()}
function cfSavePlan(){const goal=document.getElementById('cfGoal'),days=document.getElementById('cfDays'),minutes=document.getElementById('cfMinutes');state.plan.goal=goal?.value||'muscle';state.plan.days=Number(days?.value)||3;state.plan.minutes=Number(minutes?.value)||45;if(state.plan.mode==='custom'){state.plan.equipment=[...document.querySelectorAll('.equipment-choice input:checked')].map(input=>input.value)}saveState();closeSheet();renderAll();toast(`${cfPlanName()} saved`);setTimeout(openPlanSheet,180)}
cfEnsurePlan();
