import '../models/models.dart';
class ProgramGenerator {
  const ProgramGenerator();
  GeneratedProgram generate(ProgramPreferences p) {
    if (p.goal == TrainingGoal.cardio) return const GeneratedProgram(name:'ConsistiFit Cardio Foundation',split:'Run / intervals / recovery',weeks:8,workouts:[WorkoutTemplate('Easy Run',['Warm-up walk','Easy run','Cooldown']),WorkoutTemplate('Intervals',['Warm-up','Run intervals','Recovery walk','Cooldown']),WorkoutTemplate('Long Easy Session',['Easy continuous cardio','Mobility'])]);
    if (p.goal == TrainingGoal.habit) return const GeneratedProgram(name:'ConsistiFit Habit Builder',split:'Short full-body sessions',weeks:8,workouts:[WorkoutTemplate('Habit A',['Squat pattern','Push','Row','Core']),WorkoutTemplate('Habit B',['Hinge','Vertical push','Pull','Carry'])]);
    if (p.experience != ExperienceLevel.beginner && p.daysPerWeek >= 4) return const GeneratedProgram(name:'ConsistiFit Muscle Builder',split:'Upper / Lower',weeks:8,workouts:[WorkoutTemplate('Upper A',['Bench press','Row','Shoulder press','Pulldown','Arms']),WorkoutTemplate('Lower A',['Squat','Romanian deadlift','Leg curl','Calves','Core']),WorkoutTemplate('Upper B',['Incline press','Chest-supported row','Lateral raise','Pull-up','Arms']),WorkoutTemplate('Lower B',['Deadlift pattern','Split squat','Hip thrust','Leg extension','Core'])]);
    if (p.equipment == EquipmentLevel.bodyweight) return const GeneratedProgram(name:'ConsistiFit Home Foundation',split:'3-day full body',weeks:8,workouts:[WorkoutTemplate('Home A',['Tempo squat','Push-up','Backpack row','Glute bridge','Plank']),WorkoutTemplate('Home B',['Reverse lunge','Pike push-up','Doorway row','Single-leg hinge','Dead bug']),WorkoutTemplate('Home C',['Split squat','Incline push-up','Backpack row','Hip bridge','Side plank'])]);
    return GeneratedProgram(name:p.goal==TrainingGoal.strength?'ConsistiFit Strength Foundation':(p.equipment==EquipmentLevel.dumbbells?'Dumbbell Foundation':'ConsistiFit Foundation'),split:'3-day full body',weeks:8,workouts:const [WorkoutTemplate('Full Body A',['Squat / Goblet Squat','DB Bench Press','Seated Cable Row','Romanian Deadlift','Lateral Raise','Plank']),WorkoutTemplate('Full Body B',['Leg Press','Lat Pulldown','DB Shoulder Press','Leg Curl','DB Curl','Dead Bug']),WorkoutTemplate('Full Body C',['Split Squat','Incline DB Press','Chest-Supported Row','Hip Thrust','Triceps Pressdown','Calf Raise'])]);
  }
}
