insert into public.exercises(name,movement_family,equipment,muscles,replacement_group,instructions) values
('Squat / Goblet Squat','squat',array['dumbbell','barbell'],array['quads','glutes'],'squat_beginner','Brace, sit between the hips, and keep the full foot planted.'),
('Goblet Squat','squat',array['dumbbell'],array['quads','glutes'],'squat_beginner','Brace, sit between the hips, and keep the full foot planted.'),
('Back Squat','squat',array['barbell'],array['quads','glutes'],'squat_loaded','Brace before each rep and keep the bar over mid-foot.'),
('Leg Press','squat',array['machine'],array['quads','glutes'],'squat_machine','Control depth and keep hips against the pad.'),
('Split Squat','lunge',array['bodyweight','dumbbell'],array['quads','glutes'],'single_leg','Use a stable stance and lower under control.'),
('Reverse Lunge','lunge',array['bodyweight','dumbbell'],array['quads','glutes'],'single_leg','Step back softly and keep the front foot planted.'),
('Tempo Squat','squat',array['bodyweight'],array['quads','glutes'],'squat_bodyweight','Use a slow lowering phase and maintain balance through the full foot.'),
('Dumbbell Bench Press','horizontal_push',array['dumbbell'],array['chest','triceps','shoulders'],'horizontal_press','Set shoulder blades, stack wrists over elbows, and control the lowering phase.'),
('Bench Press','horizontal_push',array['barbell'],array['chest','triceps','shoulders'],'horizontal_press','Maintain a stable upper back and controlled bar path.'),
('Incline Dumbbell Press','horizontal_push',array['dumbbell'],array['upper_chest','triceps','shoulders'],'horizontal_press','Keep ribs controlled and press without shrugging.'),
('Push-up','horizontal_push',array['bodyweight'],array['chest','triceps','shoulders'],'horizontal_press','Keep the body rigid and lower the chest as one unit.'),
('Incline Push-up','horizontal_push',array['bodyweight'],array['chest','triceps','shoulders'],'horizontal_press','Keep a straight body line and lower under control.'),
('Machine Chest Press','horizontal_push',array['machine'],array['chest','triceps'],'horizontal_press','Set the seat so handles align near mid-chest.'),
('Seated Cable Row','horizontal_pull',array['cable'],array['back','biceps'],'horizontal_row','Pull elbows toward the hips without leaning back.'),
('Chest-supported Row','horizontal_pull',array['dumbbell','machine'],array['back','biceps'],'horizontal_row','Keep chest supported and pause at the top.'),
('Chest-Supported Row','horizontal_pull',array['dumbbell','machine'],array['back','biceps'],'horizontal_row','Keep chest supported and pause at the top.'),
('Dumbbell Row','horizontal_pull',array['dumbbell'],array['back','biceps'],'horizontal_row','Keep the torso stable and drive the elbow back.'),
('Backpack Row','horizontal_pull',array['bodyweight'],array['back','biceps'],'horizontal_row','Keep the torso stable and pull toward the lower ribs.'),
('Doorway Row','horizontal_pull',array['bodyweight'],array['back','biceps'],'horizontal_row','Maintain a straight body line and pull under control.'),
('Lat Pulldown','vertical_pull',array['cable'],array['lats','biceps'],'vertical_pull','Drive elbows down and avoid swinging.'),
('Pull-up / Pulldown','vertical_pull',array['bodyweight','cable'],array['lats','biceps'],'vertical_pull','Use the variation that allows controlled full-range reps.'),
('Dumbbell Shoulder Press','vertical_push',array['dumbbell'],array['shoulders','triceps'],'vertical_press','Brace and press without excessive back extension.'),
('Shoulder Press','vertical_push',array['barbell','dumbbell','machine'],array['shoulders','triceps'],'vertical_press','Brace and press without excessive back extension.'),
('Pike Push-up','vertical_push',array['bodyweight'],array['shoulders','triceps'],'vertical_press','Keep hips high and lower the head between the hands.'),
('Romanian Deadlift','hinge',array['barbell','dumbbell'],array['hamstrings','glutes','back'],'hinge','Push hips back while keeping the load close to the legs.'),
('Deadlift Pattern','hinge',array['barbell','dumbbell'],array['hamstrings','glutes','back'],'hinge','Brace, push the floor away, and keep the load close.'),
('Single-leg Hinge','hinge',array['bodyweight','dumbbell'],array['hamstrings','glutes'],'hinge','Keep hips square and move slowly through the hinge.'),
('Hip Thrust','hinge',array['barbell','machine'],array['glutes','hamstrings'],'glute_extension','Finish with ribs down and full hip extension.'),
('Glute Bridge','hinge',array['bodyweight'],array['glutes','hamstrings'],'glute_extension','Drive through the heels and finish with full hip extension.'),
('Hip Bridge','hinge',array['bodyweight'],array['glutes','hamstrings'],'glute_extension','Drive through the heels and finish with full hip extension.'),
('Leg Curl','knee_flexion',array['machine'],array['hamstrings'],'hamstring_isolation','Control both directions and avoid lifting the hips.'),
('Leg Extension','knee_extension',array['machine'],array['quads'],'quad_isolation','Control the top and lower the weight without dropping it.'),
('Lateral Raise','shoulder_abduction',array['dumbbell','cable'],array['shoulders'],'lateral_raise','Raise with control and keep traps relaxed.'),
('Triceps Pressdown','elbow_extension',array['cable'],array['triceps'],'triceps','Keep upper arms still while extending the elbows.'),
('Dumbbell Curl','elbow_flexion',array['dumbbell'],array['biceps'],'biceps','Keep elbows close and avoid swinging.'),
('Arm Superset','elbow_flexion',array['dumbbell','cable'],array['biceps','triceps'],'arms','Use controlled curls and extensions without sacrificing form.'),
('Calf Raise','ankle_extension',array['bodyweight','machine','dumbbell'],array['calves'],'calves','Use a full stretch and controlled top position.'),
('Plank','core',array['bodyweight'],array['core'],'anti_extension','Brace as if preparing for a punch and keep a neutral spine.'),
('Side Plank','core',array['bodyweight'],array['core'],'anti_lateral_flexion','Keep hips stacked and maintain a straight line.'),
('Dead Bug','core',array['bodyweight'],array['core'],'anti_extension','Keep the low back controlled while extending opposite limbs.'),
('Warm-up Walk','cardio',array['none'],array['cardio'],'cardio_easy','Walk at an easy pace until breathing and joints feel ready.'),
('Easy Run / Bike','cardio',array['none','bike'],array['cardio'],'cardio_easy','Stay at a conversational effort.'),
('Cooldown Walk','cardio',array['none'],array['recovery'],'cardio_recovery','Gradually lower effort before stopping.'),
('Warm-up','cardio',array['none'],array['cardio'],'cardio_easy','Build gradually from easy movement.'),
('Run Intervals','cardio',array['none'],array['cardio'],'cardio_intervals','Run hard enough to challenge breathing while preserving repeatable form.'),
('Cooldown','cardio',array['none'],array['recovery'],'cardio_recovery','Move easily until breathing returns toward normal.'),
('Easy Continuous Cardio','cardio',array['none','bike','rower'],array['cardio'],'cardio_easy','Keep intensity steady and sustainable.'),
('Mobility Reset','mobility',array['none'],array['recovery'],'mobility','Move gently through a comfortable range without forcing positions.')
on conflict(name) do update set
movement_family=excluded.movement_family,
equipment=excluded.equipment,
muscles=excluded.muscles,
replacement_group=excluded.replacement_group,
instructions=excluded.instructions;
