insert into public.exercises(name,movement_family,equipment,muscles,replacement_group,instructions) values
('Goblet Squat','squat',array['dumbbell'],array['quads','glutes'],'squat_beginner','Brace, sit between the hips, keep the full foot planted.'),
('Back Squat','squat',array['barbell'],array['quads','glutes'],'squat_loaded','Brace before each rep and keep the bar over mid-foot.'),
('Leg Press','squat',array['machine'],array['quads','glutes'],'squat_machine','Control depth and keep hips against the pad.'),
('Split Squat','lunge',array['bodyweight','dumbbell'],array['quads','glutes'],'single_leg','Use a stable stance and lower under control.'),
('Dumbbell Bench Press','horizontal_push',array['dumbbell'],array['chest','triceps','shoulders'],'horizontal_press','Set shoulder blades, stack wrists over elbows and control the lowering phase.'),
('Incline Dumbbell Press','horizontal_push',array['dumbbell'],array['upper_chest','triceps','shoulders'],'horizontal_press','Keep ribs controlled and press without shrugging.'),
('Push-Up','horizontal_push',array['bodyweight'],array['chest','triceps','shoulders'],'horizontal_press','Keep the body rigid and lower the chest as one unit.'),
('Machine Chest Press','horizontal_push',array['machine'],array['chest','triceps'],'horizontal_press','Set the seat so handles align near mid-chest.'),
('Seated Cable Row','horizontal_pull',array['cable'],array['back','biceps'],'horizontal_row','Pull elbows toward the hips without leaning back.'),
('Chest-Supported Row','horizontal_pull',array['dumbbell','machine'],array['back','biceps'],'horizontal_row','Keep chest supported and pause at the top.'),
('Lat Pulldown','vertical_pull',array['cable'],array['lats','biceps'],'vertical_pull','Drive elbows down and avoid swinging.'),
('Pull-Up','vertical_pull',array['bodyweight'],array['lats','biceps'],'vertical_pull','Start from control and pull chest toward the bar.'),
('Dumbbell Shoulder Press','vertical_push',array['dumbbell'],array['shoulders','triceps'],'vertical_press','Brace and press without excessive back extension.'),
('Romanian Deadlift','hinge',array['barbell','dumbbell'],array['hamstrings','glutes','back'],'hinge','Push hips back while keeping the load close to the legs.'),
('Hip Thrust','hinge',array['barbell','machine'],array['glutes','hamstrings'],'glute_extension','Finish with ribs down and full hip extension.'),
('Leg Curl','knee_flexion',array['machine'],array['hamstrings'],'hamstring_isolation','Control both directions and avoid lifting the hips.'),
('Lateral Raise','shoulder_abduction',array['dumbbell','cable'],array['shoulders'],'lateral_raise','Raise with control and keep traps relaxed.'),
('Triceps Pressdown','elbow_extension',array['cable'],array['triceps'],'triceps','Keep upper arms still while extending the elbows.'),
('Dumbbell Curl','elbow_flexion',array['dumbbell'],array['biceps'],'biceps','Keep elbows close and avoid swinging.'),
('Calf Raise','ankle_extension',array['bodyweight','machine','dumbbell'],array['calves'],'calves','Use a full stretch and controlled top position.'),
('Plank','core',array['bodyweight'],array['core'],'anti_extension','Brace as if preparing for a punch and keep a neutral spine.'),
('Dead Bug','core',array['bodyweight'],array['core'],'anti_extension','Keep the low back controlled while extending opposite limbs.')
on conflict(name) do nothing;
